### ISSUE TITLE
[建議]顯示驗證碼的圖片

### ISSUE THREAD

**Issue by Iotalh** [tyzesc/Portal-OCR#1]
因為怕辨識有可能失敗，
所以如果能保留驗證碼的圖片的話，可以再經過工人智慧驗證一次。
能不能有個選項是可以顯示圖片？

![image](https://user-images.githubusercontent.com/46061784/85207536-ff9b8700-b35b-11ea-85d4-ad6116286ab1.png)

**Comment by Iotalh** [comment]
發錯了QQ 抱歉

**Comment by tyzesc** [comment]
您好，1.1 版將會新增這項功能。 #2
